# Generated by Django 4.0.4 on 2022-06-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso_display', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='enlace',
            field=models.URLField(blank=True),
        ),
    ]
