# Generated by Django 4.0.4 on 2022-06-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso_display', '0002_curso_enlace'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='nombrePlataforma',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
