# Generated by Django 4.0.4 on 2022-06-12 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso_display', '0003_curso_nombreplataforma'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='description_vid',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='curso',
            name='imagen',
            field=models.ImageField(upload_to='curso_display'),
        ),
    ]
