# Generated by Django 4.0.4 on 2022-06-12 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso_display', '0005_remove_curso_description_vid_curso_autor_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='cursos',
            field=models.ManyToManyField(to='curso_display.curso'),
        ),
    ]
