# Generated by Django 4.0.4 on 2022-06-12 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso_display', '0006_videos_cursos'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='description_vid',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.DeleteModel(
            name='Videos',
        ),
    ]
